
include			../../rules/Makefile.top

CFLAGS			+= -msoft_float
CXXFLAGS		+= -msoft_float

MolBlockDriver-VERSION	= 1.1
KMODS			= MolBlockDriver
MolBlockDriver-OBJS	= MolBlockDevice.o

include			$(rules)/Rules.osx
include			$(rules)/Rules.make
