
include			../../../config/Makefile.top

XTARGETS		= oldworld
oldworld-OBJS		= hammerhead.o awacs.o swim3.o hacks.o scsi_main.o 53c94.o mesh.o \
			  scsi-bus.o scsi-unit.o

INCLUDES		= -I../include

include			$(rules)/Rules.make
