#
#   Creation Date: <1999/03/28 04:20:31 samuel>
#   Time-stamp: <2004/02/08 15:51:45 samuel>
#   
#	<Makefile>
#	
#	Makefile for "util/dv" target
#   
#   Copyright (C) 1999, 2000, 2002, 2004 Samuel Rydh (samuel@ibrium.se)
#   
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation
#

include		../../Makefile.top

PROGRAMS	= dv
dv-OBJS		= dumpvars.o

all-local:	
	@ln -sf $(ODIR)/dv ./

include		$(top_srcdir)/Rules.make
