
include		../../rules/Makefile.top

CFLAGS			+= -msoft_float
CXXFLAGS		+= -msoft_float

MolSCSI-VERSION		= 1.1
KMODS			= MolSCSI
MolSCSI-OBJS		= MolSCSI.o

include		$(rules)/Rules.osx
include		$(rules)/Rules.make
