#
#   Creation Date: <1999/03/28 04:20:31 samuel>
#   Time-stamp: <2002/04/30 17:53:58 samuel>
#   
#	<Makefile>
#	
#	Makefile for "util/dv" target
#   
#   Copyright (C) 1999, 2002, 2004 Samuel Rydh (samuel@ibrium.se)
#   
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation
#

include		../../Makefile.top

#CFLAGS 	= -I../../src/shared -I../../src/include -I-
PROGRAMS	= nvs
nvs-OBJS	= nvs.o

include		$(top_srcdir)/Rules.make
