#
#	<Makefile>
#	
#	Makefile for "util/img" target
#   
#   Copyright (C) 2006 Joseph Jezak (josejx@gentoo.org)
#   
#   This program is free software; you can redistribute it and/or
#   modify it under the terms of the GNU General Public License
#   as published by the Free Software Foundation
#

include		../../config/Makefile.top 

PROGRAMS		= mol-img
mol-img-OBJS		= mol-img.o mol-img-lib.o

all-local:	
	@ln -sf $(ODIR)/mol-img ./

include		../../config/Rules.make
