#!/bin/sh  
# -*- sh -*-

echo "=================================================="
echo " Invoking autoheader and autoconf."

ARCH=osx

# Cleanup certain autogenerated files
rm -f config.cache config.status include/stamp-h*
rm -rf autom4te.cache acinclude.m4
rm -f config/Makefile.defs "config/Makefile.$ARCH.defs"
rm -rf include/config.* .inc-osx

autoheader || { 
    echo "autoheader failed" ; exit 1 
}
autoconf || { 
    echo "autoconf failed" ; exit 1
}

echo " The next step is './configure' or just 'make'"
echo "=================================================="
