# 
#   Creation Date: <2003/05/31 22:10:42 samuel>
#   Time-stamp: <2003/06/16 14:55:47 samuel>
#   
#	<Makefile>
#	
#	
#   
#   Copyright (C) 2003, 2004 Samuel Rydh (samuel@ibrium.se)
#   
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License version 2
#

include		../../Makefile.top

PROGRAMS	= ofdump
ofdump-OBJS	= main.o

include		$(top_srcdir)/Rules.make
