
include		../../rules/Makefile.top

CFLAGS			+= -msoft_float
CXXFLAGS		+= -msoft_float

MolHID-VERSION		= 1.1
KMODS			= MolHID
MolHID-OBJS		= MolMouse.o MolKeyboard.o

include		$(rules)/Rules.osx
include		$(rules)/Rules.make
