
include		../../rules/Makefile.top

CFLAGS			+= -msoft_float
CXXFLAGS		+= -msoft_float

MolEnet-VERSION		= 1.1
KMODS			= MolEnet
MolEnet-OBJS		= MolEnet.o ../common/$(ODIR)/libcommon.a		  

include		$(rules)/Rules.osx
include		$(rules)/Rules.make
