/* 
 *   Creation Date: <2002/01/11 01:56:01 samuel>
 *   Time-stamp: <2004/01/30 12:12:21 samuel>
 *   
 *	<stub.c>
 *	
 *	
 *   
 *   Copyright (C) 2002, 2004 Samuel Rydh (samuel@ibrium.se)
 *   
 *   This program is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU General Public License
 *   as published by the Free Software Foundation
 *   
 */

#include "archinclude.h"
#include "version.h"
#include "alloc.h"
#include "kernel_vars.h"
#include "misc.h"

/************************************************************************/
/*	KExt magic, generated by Project Builder			*/
/************************************************************************/

#include <mach/mach_types.h>

extern kern_return_t _start(kmod_info_t *ki, void *data);
extern kern_return_t _stop(kmod_info_t *ki, void *data);
 
KMOD_EXPLICIT_DECL(se.ibrium.iokit.MolExt,  "1.1",  _start, _stop)
__private_extern__ kmod_start_func_t *_realmain = 0;
__private_extern__ kmod_stop_func_t *_antimain = 0;

