# -*- makefile -*-

obj-$(BUILD_SHEEP)	+= sheep.o
obj-$(BUILD_TUN)	+= tun.o
obj-m			+= kuname.o

sheep.o tun.o: .kuname
.kuname: kuname.o
	strings $< | grep -- '-MAGIC-' | sed -e s/-MAGIC-// > $@


include $(TOPDIR)/Rules.make
